### ISSUE TITLE
Привет от наставника 👋

### ISSUE THREAD

**Issue by funkylen** [Xequrt/currency_converter#1]
https://github.com/Xequrt/currency_converter/blob/4e918fb8a42910cd150e156ee0cee61a16ff8e85/main.py#L10

Небезопасное обращение к ключу data. Стоит делать через get с переданным стандартным значением, чтобы исключить поломку проекта.

---

https://github.com/Xequrt/currency_converter/blob/4e918fb8a42910cd150e156ee0cee61a16ff8e85/main.py#L21-L29

Можно записать проще, если убрать try/except и использовать if с in вместо not in. Таким образом у тебя будет классическая рекурсия с условием выхода из функции.

---

https://github.com/Xequrt/currency_converter/blob/4e918fb8a42910cd150e156ee0cee61a16ff8e85/main.py#L59

Эти строки не работают, потому что твой amount_input всегда строка – ввод от пользователя. isinstance проверяет именно тип, он не приводит значения.

---

Если хочешь сделать бесконечный ввод для количества, ты можешь попробовать реализовать такую же функцию с рекурсией как и для валюты.

**Comment by Xequrt** [comment]
Здравствуйте, спасибо за ответ, я пытался сделать ввод количества валюты бесконечным, но сил не хватило) Ввод названия валюты получилось сделать чудным образом, не совсем понял, как работает) Точнее, как работает, логика ясна, но как получилось, не понял ) По поводу того, почему в комментариях не работает, понял, спасибо. А вот с методом .get и ответом ['data'] не все так понятно, буду надеяться, что во время обучения станет яснее)
